version: '3'
services:

  blablacar.api.spring:
    build: ./spring
    ports:
      - '8080:8080'
    networks:
      - blablacar

  blablacar.bd.mysql:
    image: mysql:8.3.0
    ports:
      - '3306:3306'
    volumes:
      - ./volumes/db/mysql/main:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
    networks:
      - blablacar

  blablacar.phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - '8088:80'
    env_file:
      - .env
    networks:
      - blablacar

networks:
  blablacar:
    driver: bridge